// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCESsbbPJp5C6qtd_yc2fPV-j5ub0qs4F0',
    appId: '1:603355117255:web:c34a15d7a88baeebdbb0e2',
    messagingSenderId: '603355117255',
    projectId: 'book-event-917db',
    authDomain: 'book-event-917db.firebaseapp.com',
    storageBucket: 'book-event-917db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7iPZAqyF9S4hm4S2ZHnw0XCP3H8DrizA',
    appId: '1:603355117255:android:e408d2dc68a91e68dbb0e2',
    messagingSenderId: '603355117255',
    projectId: 'book-event-917db',
    storageBucket: 'book-event-917db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClERbYoum6jIzcGsTjto9Oxiq7eaY8LHA',
    appId: '1:603355117255:ios:ef41edf4409ee494dbb0e2',
    messagingSenderId: '603355117255',
    projectId: 'book-event-917db',
    storageBucket: 'book-event-917db.firebasestorage.app',
    iosBundleId: 'com.example.bookEvent',
  );
}
